# Generated by Django 5.0.4 on 2024-04-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('nuevo', models.BooleanField(default=True)),
            ],
        ),
    ]
